version: "1.0.0.{build}"

platform: Any CPU
configuration: Release

init:
- cmd: echo %APPVEYOR_BUILD_VERSION%

cache: 
- packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

before_build:
- cmd: appveyor-retry nuget restore -verbosity detailed

build:
  project: Asap2.sln
  verbosity: minimal

after_build:
- ps: |
    $suffix = Get-Date -format "yyyyMMddhhss"
    $semver = ${env:APPVEYOR_BUILD_VERSION} -ireplace '(\d+.\d+.\d+).(\d+)', "`$1-ci-`$2-${env:APPVEYOR_REPO_BRANCH}"
    $semver = $semver.Substring(0, [System.Math]::Min(20, $semver.Length))
    nuget pack Asap2\Asap2.csproj -properties "Configuration=${env:CONFIGURATION};Platform=AnyCPU" -symbols -version $semver

artifacts:
- path: '*.nupkg'